
use_frameworks!

target 'TestErik' do
  platform :ios, '9.0'
	pod 'Erik', :path => '../Erik.podspec'
end

target 'TestErikOSX' do
  platform :osx, '10.10'
    pod 'Erik', :path => '../Erik.podspec'
end

